SRC_DIR = src
BIN_DIR = bin

calculo:
	g++ -o $(BIN_DIR)/calculo $(SRC_DIR)/calculo.cpp
	./$(BIN_DIR)/calculo.cpp
	rm $(BIN_DIR)/calculo

lista:
	g++ -o $(BIN_DIR)/lista $(SRC_DIR)/lista.cpp
	./$(BIN_DIR)/lista
	rm $(BIN_DIR)/lista